source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
inhibit_all_warnings!

target 'Gravity' do
    pod 'RestKit', '~> 0.27.0'
    pod 'MBProgressHUD', '~> 0.9.2'
    pod 'LUKeychainAccess', '~> 1.2.5'
    pod 'SDWebImage', '~> 3.8.1'
    pod 'UIActivityIndicator-for-SDWebImage', '~> 1.2'
    pod 'SZTextView', '~> 1.2.2'
    pod 'SEHumanizedTimeDiff', '~> 0.0.1'
    pod 'TWMessageBarManager', '~> 1.8.1'
    pod 'SHSPhoneComponent', '~> 2.15'
    pod 'UIAlertView+Blocks', '~> 0.9'
    pod 'INTULocationManager', '~> 4.2.0'
    pod 'DACircularProgress', '~> 2.3.1'
    pod 'pop', '1.0.8'
    pod 'Stripe', '~> 5.1.4'
    pod 'Flurry-iOS-SDK', '~> 7.6.6'
    pod 'ObjectiveLuhn'
    pod 'LEAlertController', :git => 'https://github.com/brightsider/LEAlertController.git', :commit => 'f7fda7a60b'
end