"""Allow guest transactions: make Transaction.user_id and GoalProgressLog.users_id nullable

Revision ID: 2688c1fbf109
Revises: 3905ffdec2f9
Create Date: 2025-10-21 15:16:01.024228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2688c1fbf109'
down_revision = '3905ffdec2f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goals_progress_log', schema=None) as batch_op:
        batch_op.alter_column('users_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('goals_progress_log', schema=None) as batch_op:
        batch_op.alter_column('users_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
