"""Add notification_settings and Transaction model

Revision ID: 32000d86a46a
Revises: b13300565dc5
Create Date: 2025-09-11 13:44:40.406960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32000d86a46a'
down_revision = 'b13300565dc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('portal_id', sa.Integer(), nullable=False),
    sa.Column('goal_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('transaction_type', sa.String(length=50), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('stripe_payment_intent_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['portal_id'], ['portals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_goal_id'), ['goal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_portal_id'), ['portal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_stripe_payment_intent_id'), ['stripe_payment_intent_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_transactions_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notification_settings', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('notification_settings')

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_user_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_stripe_payment_intent_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_portal_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_goal_id'))

    op.drop_table('transactions')
    # ### end Alembic commands ###
