"""Add stripe_account_approved and stripe_connect_requested to Portal

Revision ID: 3905ffdec2f9
Revises: 4e2a292a92be
Create Date: 2025-10-10 10:05:11.299454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3905ffdec2f9'
down_revision = '4e2a292a92be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_account_approved', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('stripe_connect_requested', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portals', schema=None) as batch_op:
        batch_op.drop_column('stripe_connect_requested')
        batch_op.drop_column('stripe_account_approved')

    # ### end Alembic commands ###
