"""Add user photos, photo social features, and portal text position

Revision ID: 4cc981a56536
Revises: 7362772a1ed0
Create Date: 2026-02-04 17:46:56.907783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cc981a56536'
down_revision = '7362772a1ed0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('users_id', sa.Integer(), nullable=False),
    sa.Column('s3_gr_hash', sa.String(length=255), nullable=False),
    sa.Column('caption', sa.String(length=500), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['s3_gr_hash'], ['s3_content.gr_hash'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_photos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_photos_s3_gr_hash'), ['s3_gr_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_photos_users_id'), ['users_id'], unique=False)

    op.create_table('photo_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('photo_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['photo_id'], ['user_photos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('photo_comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_photo_comments_photo_id'), ['photo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_photo_comments_user_id'), ['user_id'], unique=False)

    op.create_table('photo_likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('photo_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['photo_id'], ['user_photos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('photo_id', 'user_id', name='unique_user_like_per_photo')
    )
    with op.batch_alter_table('photo_likes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_photo_likes_photo_id'), ['photo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_photo_likes_user_id'), ['user_id'], unique=False)

    op.create_table('photo_reactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('photo_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('emoji', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['photo_id'], ['user_photos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('photo_id', 'user_id', 'emoji', name='unique_user_emoji_per_photo')
    )
    with op.batch_alter_table('photo_reactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_photo_reactions_photo_id'), ['photo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_photo_reactions_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('portals_texts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portals_texts', schema=None) as batch_op:
        batch_op.drop_column('position')

    with op.batch_alter_table('photo_reactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_photo_reactions_user_id'))
        batch_op.drop_index(batch_op.f('ix_photo_reactions_photo_id'))

    op.drop_table('photo_reactions')
    with op.batch_alter_table('photo_likes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_photo_likes_user_id'))
        batch_op.drop_index(batch_op.f('ix_photo_likes_photo_id'))

    op.drop_table('photo_likes')
    with op.batch_alter_table('photo_comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_photo_comments_user_id'))
        batch_op.drop_index(batch_op.f('ix_photo_comments_photo_id'))

    op.drop_table('photo_comments')
    with op.batch_alter_table('user_photos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_photos_users_id'))
        batch_op.drop_index(batch_op.f('ix_user_photos_s3_gr_hash'))

    op.drop_table('user_photos')
    # ### end Alembic commands ###
