"""Add Write and Messaging enhancements

Revision ID: 7362772a1ed0
Revises: 2688c1fbf109
Create Date: 2025-12-05 10:28:49.532675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7362772a1ed0'
down_revision = '2688c1fbf109'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=100), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['direct_messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('message_attachments', schema=None) as batch_op:
        batch_op.create_index('idx_message_attachments_message_id', ['message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_attachments_message_id'), ['message_id'], unique=False)

    op.create_table('message_edit_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('previous_text', sa.Text(), nullable=False),
    sa.Column('edited_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['direct_messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('message_edit_history', schema=None) as batch_op:
        batch_op.create_index('idx_message_edit_history_message_id', ['message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_edit_history_message_id'), ['message_id'], unique=False)

    op.create_table('message_reactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('emoji', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['direct_messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id', 'user_id', 'emoji', name='unique_user_emoji_per_message')
    )
    with op.batch_alter_table('message_reactions', schema=None) as batch_op:
        batch_op.create_index('idx_message_reactions_message_id', ['message_id'], unique=False)
        batch_op.create_index('idx_message_reactions_user_id', ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_reactions_message_id'), ['message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_reactions_user_id'), ['user_id'], unique=False)

    op.create_table('group_message_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=100), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['group_messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('group_message_attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_group_message_attachments_message_id'), ['message_id'], unique=False)

    op.create_table('group_message_edit_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('previous_text', sa.Text(), nullable=False),
    sa.Column('edited_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['group_messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('group_message_edit_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_group_message_edit_history_message_id'), ['message_id'], unique=False)

    op.create_table('group_message_reactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('emoji', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['group_messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id', 'user_id', 'emoji', name='unique_user_emoji_per_group_message')
    )
    with op.batch_alter_table('group_message_reactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_group_message_reactions_message_id'), ['message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_group_message_reactions_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('direct_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('edited_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='false'))

    with op.batch_alter_table('group_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('edited_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='false'))

    with op.batch_alter_table('writes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content_format', sa.String(length=10), nullable=True, server_default='plain'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('writes', schema=None) as batch_op:
        batch_op.drop_column('content_format')

    with op.batch_alter_table('group_messages', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('edited_at')

    with op.batch_alter_table('direct_messages', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('edited_at')

    with op.batch_alter_table('group_message_reactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_group_message_reactions_user_id'))
        batch_op.drop_index(batch_op.f('ix_group_message_reactions_message_id'))

    op.drop_table('group_message_reactions')
    with op.batch_alter_table('group_message_edit_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_group_message_edit_history_message_id'))

    op.drop_table('group_message_edit_history')
    with op.batch_alter_table('group_message_attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_group_message_attachments_message_id'))

    op.drop_table('group_message_attachments')
    with op.batch_alter_table('message_reactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_reactions_user_id'))
        batch_op.drop_index(batch_op.f('ix_message_reactions_message_id'))
        batch_op.drop_index('idx_message_reactions_user_id')
        batch_op.drop_index('idx_message_reactions_message_id')

    op.drop_table('message_reactions')
    with op.batch_alter_table('message_edit_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_edit_history_message_id'))
        batch_op.drop_index('idx_message_edit_history_message_id')

    op.drop_table('message_edit_history')
    with op.batch_alter_table('message_attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_attachments_message_id'))
        batch_op.drop_index('idx_message_attachments_message_id')

    op.drop_table('message_attachments')
    # ### end Alembic commands ###
