"""Add last_read_message_id to chats_users

Revision ID: 85b61704b80c
Revises: b31f33e84248
Create Date: 2025-08-20 15:53:58.762344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85b61704b80c'
down_revision = 'b31f33e84248'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chats_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_read_message_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chats_users', schema=None) as batch_op:
        batch_op.drop_column('last_read_message_id')

    # ### end Alembic commands ###
