"""Initial migration

Revision ID: 9b4ae1baf414
Revises: 
Create Date: 2025-06-25 20:20:22.169034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b4ae1baf414'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('cities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('goal_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reporting_increments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('s3_content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gr_hash', sa.String(length=255), nullable=False),
    sa.Column('tbl_id', sa.Integer(), nullable=False),
    sa.Column('tbl_index', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=True),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('file_type', sa.String(length=50), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('s3_content', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_s3_content_gr_hash'), ['gr_hash'], unique=True)

    op.create_table('skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('parent', sa.Integer(), nullable=True),
    sa.Column('visible', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['parent'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('visible', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('goal_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('goal_types_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['goal_types_id'], ['goal_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('about', sa.Text(), nullable=True),
    sa.Column('broadcast', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('cities_id', sa.Integer(), nullable=True),
    sa.Column('users_types_id', sa.Integer(), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('fname', sa.String(length=100), nullable=True),
    sa.Column('lname', sa.String(length=100), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('device_token', sa.String(length=255), nullable=True),
    sa.Column('twitter_id', sa.String(length=100), nullable=True),
    sa.Column('manual_city', sa.String(length=100), nullable=True),
    sa.Column('other_skill', sa.String(length=255), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('email_verification_token', sa.String(length=128), nullable=True),
    sa.Column('profile_picture_url', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['users_types_id'], ['user_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_phone'), ['phone'], unique=False)

    op.create_table('chats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('direct_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('password_updaters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('users_id', sa.Integer(), nullable=False),
    sa.Column('hash', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('portals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('users_id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('subtitle', sa.String(length=255), nullable=True),
    sa.Column('categories_id', sa.Integer(), nullable=True),
    sa.Column('cities_id', sa.Integer(), nullable=True),
    sa.Column('about', sa.Text(), nullable=True),
    sa.Column('visible', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['categories_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['cities_id'], ['cities.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('portals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_portals_categories_id'), ['categories_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_portals_cities_id'), ['cities_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_portals_lead_id'), ['lead_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_portals_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_portals_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_portals_users_id'), ['users_id'], unique=False)

    op.create_table('users_followers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('users_id1', sa.Integer(), nullable=False),
    sa.Column('users_id2', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['users_id1'], ['users.id'], ),
    sa.ForeignKeyConstraint(['users_id2'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('users_id1', 'users_id2', name='uq_users_followers_pair')
    )
    with op.batch_alter_table('users_followers', schema=None) as batch_op:
        batch_op.create_index('ix_users_followers_pair', ['users_id1', 'users_id2'], unique=False)

    op.create_table('users_network',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('users_id1', sa.Integer(), nullable=False),
    sa.Column('users_id2', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['users_id1'], ['users.id'], ),
    sa.ForeignKeyConstraint(['users_id2'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('users_id1', 'users_id2', name='uq_users_network_pair')
    )
    with op.batch_alter_table('users_network', schema=None) as batch_op:
        batch_op.create_index('ix_users_network_pair', ['users_id1', 'users_id2'], unique=False)

    op.create_table('users_skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('users_id', sa.Integer(), nullable=False),
    sa.Column('skills_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['skills_id'], ['skills.id'], ),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('users_id', 'skills_id', name='uq_users_skills_pair')
    )
    with op.batch_alter_table('users_skills', schema=None) as batch_op:
        batch_op.create_index('ix_users_skills_pair', ['users_id', 'skills_id'], unique=False)

    op.create_table('writes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('users_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('writes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_writes_users_id'), ['users_id'], unique=False)

    op.create_table('chats_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chats_id', sa.Integer(), nullable=False),
    sa.Column('users_id', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chats_id'], ['chats.id'], ),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('subtitle', sa.String(length=255), nullable=True),
    sa.Column('users_id', sa.Integer(), nullable=False),
    sa.Column('portals_id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('quota', sa.Integer(), nullable=True),
    sa.Column('filled_quota', sa.Integer(), nullable=True),
    sa.Column('quota_is_reached_note', sa.Boolean(), nullable=True),
    sa.Column('goal_types_id', sa.Integer(), nullable=False),
    sa.Column('goal_metrics_id', sa.Integer(), nullable=False),
    sa.Column('rep_commission', sa.Float(), nullable=True),
    sa.Column('reporting_increments_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['goal_metrics_id'], ['goal_metrics.id'], ),
    sa.ForeignKeyConstraint(['goal_types_id'], ['goal_types.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['portals_id'], ['portals.id'], ),
    sa.ForeignKeyConstraint(['reporting_increments_id'], ['reporting_increments.id'], ),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_goals_goal_metrics_id'), ['goal_metrics_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_goals_goal_types_id'), ['goal_types_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_goals_portals_id'), ['portals_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_goals_reporting_increments_id'), ['reporting_increments_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_goals_users_id'), ['users_id'], unique=False)

    op.create_table('group_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('portal_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portal_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['portal_id'], ['portals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('portal_invites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portal_id', sa.Integer(), nullable=False),
    sa.Column('invited_by_id', sa.Integer(), nullable=False),
    sa.Column('invited_user_id', sa.Integer(), nullable=True),
    sa.Column('invitee_email', sa.String(length=255), nullable=True),
    sa.Column('invitee_phone', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['invited_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['invited_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['portal_id'], ['portals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('portal_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portal_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['portal_id'], ['portals.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('portal_id', 'user_id', name='uq_portal_user_pair')
    )
    with op.batch_alter_table('portal_users', schema=None) as batch_op:
        batch_op.create_index('ix_portal_user_role', ['portal_id', 'user_id', 'role'], unique=False)
        batch_op.create_index(batch_op.f('ix_portal_users_portal_id'), ['portal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_portal_users_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_portal_users_user_id'), ['user_id'], unique=False)

    op.create_table('portals_graphic_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portals_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['portals_id'], ['portals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('portals_graphic_sections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_portals_graphic_sections_portals_id'), ['portals_id'], unique=False)

    op.create_table('portals_texts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portal_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('section', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['portal_id'], ['portals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('portals_texts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_portals_texts_portal_id'), ['portal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_portals_texts_section'), ['section'], unique=False)

    op.create_table('goals_pre_invites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('users_id', sa.Integer(), nullable=False),
    sa.Column('goals_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('identifier', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['goals_id'], ['goals.id'], ),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('goals_progress_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('users_id', sa.Integer(), nullable=False),
    sa.Column('goals_id', sa.Integer(), nullable=False),
    sa.Column('added_value', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['goals_id'], ['goals.id'], ),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('goals_progress_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_goals_progress_log_goals_id'), ['goals_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_goals_progress_log_users_id'), ['users_id'], unique=False)

    op.create_table('goals_team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('users_id1', sa.Integer(), nullable=False),
    sa.Column('users_id2', sa.Integer(), nullable=False),
    sa.Column('goals_id', sa.Integer(), nullable=False),
    sa.Column('confirmed', sa.Integer(), nullable=True),
    sa.Column('read1', sa.Boolean(), nullable=True),
    sa.Column('read2', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['goals_id'], ['goals.id'], ),
    sa.ForeignKeyConstraint(['users_id1'], ['users.id'], ),
    sa.ForeignKeyConstraint(['users_id2'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('portals_graphic_sections_s3_content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portals_graphic_sections_id', sa.Integer(), nullable=False),
    sa.Column('s3_gr_hash', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['portals_graphic_sections_id'], ['portals_graphic_sections.id'], ),
    sa.ForeignKeyConstraint(['s3_gr_hash'], ['s3_content.gr_hash'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('portals_graphic_sections_id', 's3_gr_hash', name='uq_section_file')
    )
    with op.batch_alter_table('portals_graphic_sections_s3_content', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_portals_graphic_sections_s3_content_portals_graphic_sections_id'), ['portals_graphic_sections_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_portals_graphic_sections_s3_content_s3_gr_hash'), ['s3_gr_hash'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portals_graphic_sections_s3_content', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_portals_graphic_sections_s3_content_s3_gr_hash'))
        batch_op.drop_index(batch_op.f('ix_portals_graphic_sections_s3_content_portals_graphic_sections_id'))

    op.drop_table('portals_graphic_sections_s3_content')
    op.drop_table('goals_team')
    with op.batch_alter_table('goals_progress_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_goals_progress_log_users_id'))
        batch_op.drop_index(batch_op.f('ix_goals_progress_log_goals_id'))

    op.drop_table('goals_progress_log')
    op.drop_table('goals_pre_invites')
    with op.batch_alter_table('portals_texts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_portals_texts_section'))
        batch_op.drop_index(batch_op.f('ix_portals_texts_portal_id'))

    op.drop_table('portals_texts')
    with op.batch_alter_table('portals_graphic_sections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_portals_graphic_sections_portals_id'))

    op.drop_table('portals_graphic_sections')
    with op.batch_alter_table('portal_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_portal_users_user_id'))
        batch_op.drop_index(batch_op.f('ix_portal_users_role'))
        batch_op.drop_index(batch_op.f('ix_portal_users_portal_id'))
        batch_op.drop_index('ix_portal_user_role')

    op.drop_table('portal_users')
    op.drop_table('portal_invites')
    op.drop_table('portal_events')
    op.drop_table('group_messages')
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_goals_users_id'))
        batch_op.drop_index(batch_op.f('ix_goals_reporting_increments_id'))
        batch_op.drop_index(batch_op.f('ix_goals_portals_id'))
        batch_op.drop_index(batch_op.f('ix_goals_goal_types_id'))
        batch_op.drop_index(batch_op.f('ix_goals_goal_metrics_id'))

    op.drop_table('goals')
    op.drop_table('chats_users')
    with op.batch_alter_table('writes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_writes_users_id'))

    op.drop_table('writes')
    with op.batch_alter_table('users_skills', schema=None) as batch_op:
        batch_op.drop_index('ix_users_skills_pair')

    op.drop_table('users_skills')
    with op.batch_alter_table('users_network', schema=None) as batch_op:
        batch_op.drop_index('ix_users_network_pair')

    op.drop_table('users_network')
    with op.batch_alter_table('users_followers', schema=None) as batch_op:
        batch_op.drop_index('ix_users_followers_pair')

    op.drop_table('users_followers')
    with op.batch_alter_table('portals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_portals_users_id'))
        batch_op.drop_index(batch_op.f('ix_portals_status'))
        batch_op.drop_index(batch_op.f('ix_portals_name'))
        batch_op.drop_index(batch_op.f('ix_portals_lead_id'))
        batch_op.drop_index(batch_op.f('ix_portals_cities_id'))
        batch_op.drop_index(batch_op.f('ix_portals_categories_id'))

    op.drop_table('portals')
    op.drop_table('password_updaters')
    op.drop_table('direct_messages')
    op.drop_table('chats')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_phone'))

    op.drop_table('users')
    op.drop_table('goal_metrics')
    op.drop_table('user_types')
    op.drop_table('skills')
    with op.batch_alter_table('s3_content', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_s3_content_gr_hash'))

    op.drop_table('s3_content')
    op.drop_table('reporting_increments')
    op.drop_table('goal_types')
    op.drop_table('cities')
    op.drop_table('categories')
    # ### end Alembic commands ###
