"""Add portals_users_share table

Revision ID: 9bbf8ecf7d0c
Revises: 9b4ae1baf414
Create Date: 2025-06-29 18:31:45.496261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bbf8ecf7d0c'
down_revision = '9b4ae1baf414'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goal_progress_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('goal_progress_id', sa.Integer(), nullable=False),
    sa.Column('file_url', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages_read',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('users_id', sa.Integer(), nullable=False),
    sa.Column('messages_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('portals_users_share',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portals_id', sa.Integer(), nullable=False),
    sa.Column('users_id', sa.Integer(), nullable=False),
    sa.Column('shared_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['portals_id'], ['portals.id'], ),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('portals_users_share', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_portals_users_share_portals_id'), ['portals_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_portals_users_share_users_id'), ['users_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portals_users_share', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_portals_users_share_users_id'))
        batch_op.drop_index(batch_op.f('ix_portals_users_share_portals_id'))

    op.drop_table('portals_users_share')
    op.drop_table('messages_read')
    op.drop_table('goal_progress_files')
    # ### end Alembic commands ###
