"""Add Stripe fields to Portal and User

Revision ID: b13300565dc5
Revises: 85b61704b80c
Create Date: 2025-09-10 20:06:05.105245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b13300565dc5'
down_revision = '85b61704b80c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_account_id', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('stripe_account_status', sa.Boolean(), nullable=True))
        batch_op.create_index(batch_op.f('ix_portals_stripe_account_id'), ['stripe_account_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_customer_id', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('stripe_account_id', sa.String(length=128), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_stripe_account_id'), ['stripe_account_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_stripe_account_id'))
        batch_op.drop_column('stripe_account_id')
        batch_op.drop_column('stripe_customer_id')

    with op.batch_alter_table('portals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_portals_stripe_account_id'))
        batch_op.drop_column('stripe_account_status')
        batch_op.drop_column('stripe_account_id')

    # ### end Alembic commands ###
