"""Add FlaggedPortal model

Revision ID: b31f33e84248
Revises: 5fa2f4928cfa
Create Date: 2025-07-30 20:42:30.659228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b31f33e84248'
down_revision = '5fa2f4928cfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flagged_portals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flagger_id', sa.Integer(), nullable=False),
    sa.Column('portal_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['flagger_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['portal_id'], ['portals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('flagger_id', 'portal_id', name='uq_flagged_portal_pair')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flagged_portals')
    # ### end Alembic commands ###
