"""Update Goal model: make portals_id nullable

Revision ID: c196646a34b6
Revises: 9bbf8ecf7d0c
Create Date: 2025-06-30 20:42:45.613769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c196646a34b6'
down_revision = '9bbf8ecf7d0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.alter_column('portals_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.alter_column('portals_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
