"""Add portal_type and event fields to portals

Revision ID: f3a8d921c047
Revises: 4cc981a56536
Create Date: 2026-04-16 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3a8d921c047'
down_revision = '4cc981a56536'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('portal_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('event_datetime', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('event_location', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('event_timezone', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portals', schema=None) as batch_op:
        batch_op.drop_column('event_timezone')
        batch_op.drop_column('event_location')
        batch_op.drop_column('event_datetime')
        batch_op.drop_column('portal_type')

    # ### end Alembic commands ###
